set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_ADDR[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_ADDR[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_ADDR[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_ADDR[3]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_ADDR[4]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_ADDR[5]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_ADDR[6]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_ADDR[7]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_ADDR[8]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_ADDR[9]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_ADDR[10]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_ADDR[11]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_ADDR[12]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_ADDR[13]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_ADDR[14]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_BA[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_BA[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_BA[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_CAS_N
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_CKE
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.5-V SSTL CLASS I" -to HPS_DDR3_CK_N
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.5-V SSTL CLASS I" -to HPS_DDR3_CK_P
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_CS_N
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_DM[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_DM[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_DM[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_DM[3]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_DQ[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_DQ[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_DQ[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_DQ[3]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_DQ[4]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_DQ[5]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_DQ[6]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_DQ[7]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_DQ[8]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_DQ[9]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_DQ[10]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_DQ[11]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_DQ[12]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_DQ[13]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_DQ[14]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_DQ[15]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_DQ[16]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_DQ[17]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_DQ[18]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_DQ[19]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_DQ[20]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_DQ[21]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_DQ[22]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_DQ[23]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_DQ[24]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_DQ[25]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_DQ[26]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_DQ[27]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_DQ[28]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_DQ[29]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_DQ[30]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_DQ[31]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.5-V SSTL CLASS I" -to HPS_DDR3_DQS_N[0]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.5-V SSTL CLASS I" -to HPS_DDR3_DQS_N[1]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.5-V SSTL CLASS I" -to HPS_DDR3_DQS_N[2]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.5-V SSTL CLASS I" -to HPS_DDR3_DQS_N[3]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.5-V SSTL CLASS I" -to HPS_DDR3_DQS_P[0]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.5-V SSTL CLASS I" -to HPS_DDR3_DQS_P[1]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.5-V SSTL CLASS I" -to HPS_DDR3_DQS_P[2]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.5-V SSTL CLASS I" -to HPS_DDR3_DQS_P[3]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_ODT
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_RAS_N
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_RESET_N
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_RZQ
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I" -to HPS_DDR3_WE_N

set_location_assignment PIN_F26 -to HPS_DDR3_ADDR[0]
set_location_assignment PIN_G30 -to HPS_DDR3_ADDR[1]
set_location_assignment PIN_F28 -to HPS_DDR3_ADDR[2]
set_location_assignment PIN_F30 -to HPS_DDR3_ADDR[3]
set_location_assignment PIN_J25 -to HPS_DDR3_ADDR[4]
set_location_assignment PIN_J27 -to HPS_DDR3_ADDR[5]
set_location_assignment PIN_F29 -to HPS_DDR3_ADDR[6]
set_location_assignment PIN_E28 -to HPS_DDR3_ADDR[7]
set_location_assignment PIN_H27 -to HPS_DDR3_ADDR[8]
set_location_assignment PIN_G26 -to HPS_DDR3_ADDR[9]
set_location_assignment PIN_D29 -to HPS_DDR3_ADDR[10]
set_location_assignment PIN_C30 -to HPS_DDR3_ADDR[11]
set_location_assignment PIN_B30 -to HPS_DDR3_ADDR[12]
set_location_assignment PIN_C29 -to HPS_DDR3_ADDR[13]
set_location_assignment PIN_H25 -to HPS_DDR3_ADDR[14]
set_location_assignment PIN_E29 -to HPS_DDR3_BA[0]
set_location_assignment PIN_J24 -to HPS_DDR3_BA[1]
set_location_assignment PIN_J23 -to HPS_DDR3_BA[2]
set_location_assignment PIN_E27 -to HPS_DDR3_CAS_N
set_location_assignment PIN_L29 -to HPS_DDR3_CKE
set_location_assignment PIN_L23 -to HPS_DDR3_CK_N
set_location_assignment PIN_M23 -to HPS_DDR3_CK_P
set_location_assignment PIN_H24 -to HPS_DDR3_CS_N
set_location_assignment PIN_K28 -to HPS_DDR3_DM[0]
set_location_assignment PIN_M28 -to HPS_DDR3_DM[1]
set_location_assignment PIN_R28 -to HPS_DDR3_DM[2]
set_location_assignment PIN_W30 -to HPS_DDR3_DM[3]
set_location_assignment PIN_K23 -to HPS_DDR3_DQ[0]
set_location_assignment PIN_K22 -to HPS_DDR3_DQ[1]
set_location_assignment PIN_H30 -to HPS_DDR3_DQ[2]
set_location_assignment PIN_G28 -to HPS_DDR3_DQ[3]
set_location_assignment PIN_L25 -to HPS_DDR3_DQ[4]
set_location_assignment PIN_L24 -to HPS_DDR3_DQ[5]
set_location_assignment PIN_J30 -to HPS_DDR3_DQ[6]
set_location_assignment PIN_J29 -to HPS_DDR3_DQ[7]
set_location_assignment PIN_K26 -to HPS_DDR3_DQ[8]
set_location_assignment PIN_L26 -to HPS_DDR3_DQ[9]
set_location_assignment PIN_K29 -to HPS_DDR3_DQ[10]
set_location_assignment PIN_K27 -to HPS_DDR3_DQ[11]
set_location_assignment PIN_M26 -to HPS_DDR3_DQ[12]
set_location_assignment PIN_M27 -to HPS_DDR3_DQ[13]
set_location_assignment PIN_L28 -to HPS_DDR3_DQ[14]
set_location_assignment PIN_M30 -to HPS_DDR3_DQ[15]
set_location_assignment PIN_U26 -to HPS_DDR3_DQ[16]
set_location_assignment PIN_T26 -to HPS_DDR3_DQ[17]
set_location_assignment PIN_N29 -to HPS_DDR3_DQ[18]
set_location_assignment PIN_N28 -to HPS_DDR3_DQ[19]
set_location_assignment PIN_P26 -to HPS_DDR3_DQ[20]
set_location_assignment PIN_P27 -to HPS_DDR3_DQ[21]
set_location_assignment PIN_N27 -to HPS_DDR3_DQ[22]
set_location_assignment PIN_R29 -to HPS_DDR3_DQ[23]
set_location_assignment PIN_P24 -to HPS_DDR3_DQ[24]
set_location_assignment PIN_P25 -to HPS_DDR3_DQ[25]
set_location_assignment PIN_T29 -to HPS_DDR3_DQ[26]
set_location_assignment PIN_T28 -to HPS_DDR3_DQ[27]
set_location_assignment PIN_R27 -to HPS_DDR3_DQ[28]
set_location_assignment PIN_R26 -to HPS_DDR3_DQ[29]
set_location_assignment PIN_V30 -to HPS_DDR3_DQ[30]
set_location_assignment PIN_W29 -to HPS_DDR3_DQ[31]
set_location_assignment PIN_M19 -to HPS_DDR3_DQS_N[0]
set_location_assignment PIN_N24 -to HPS_DDR3_DQS_N[1]
set_location_assignment PIN_R18 -to HPS_DDR3_DQS_N[2]
set_location_assignment PIN_R21 -to HPS_DDR3_DQS_N[3]
set_location_assignment PIN_N18 -to HPS_DDR3_DQS_P[0]
set_location_assignment PIN_N25 -to HPS_DDR3_DQS_P[1]
set_location_assignment PIN_R19 -to HPS_DDR3_DQS_P[2]
set_location_assignment PIN_R22 -to HPS_DDR3_DQS_P[3]
set_location_assignment PIN_H28 -to HPS_DDR3_ODT
set_location_assignment PIN_D30 -to HPS_DDR3_RAS_N
set_location_assignment PIN_P30 -to HPS_DDR3_RESET_N
set_location_assignment PIN_D27 -to HPS_DDR3_RZQ
set_location_assignment PIN_C28 -to HPS_DDR3_WE_N
