set_false_path -from [get_ports hps_io_hps_io_usb1_inst_D0] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_usb1_inst_D0]
set_false_path -from [get_ports hps_io_hps_io_usb1_inst_D1] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_usb1_inst_D1]
set_false_path -from [get_ports hps_io_hps_io_usb1_inst_D2] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_usb1_inst_D2]
set_false_path -from [get_ports hps_io_hps_io_usb1_inst_D3] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_usb1_inst_D3]
set_false_path -from [get_ports hps_io_hps_io_usb1_inst_D4] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_usb1_inst_D4]
set_false_path -from [get_ports hps_io_hps_io_usb1_inst_D5] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_usb1_inst_D5]
set_false_path -from [get_ports hps_io_hps_io_usb1_inst_D6] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_usb1_inst_D6]
set_false_path -from [get_ports hps_io_hps_io_usb1_inst_D7] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_usb1_inst_D7]
set_false_path -from [get_ports hps_io_hps_io_usb1_inst_CLK] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_usb1_inst_STP]
set_false_path -from [get_ports hps_io_hps_io_usb1_inst_DIR] -to *
set_false_path -from [get_ports hps_io_hps_io_usb1_inst_NXT] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_spim1_inst_CLK]
set_false_path -from * -to [get_ports hps_io_hps_io_spim1_inst_MOSI]
set_false_path -from [get_ports hps_io_hps_io_spim1_inst_MISO] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_spim1_inst_SS0]
set_false_path -from [get_ports hps_io_hps_io_i2c1_inst_SDA] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_i2c1_inst_SDA]
set_false_path -from [get_ports hps_io_hps_io_i2c1_inst_SCL] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_i2c1_inst_SCL]
set_false_path -from [get_ports hps_io_hps_io_can1_inst_RX] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_can1_inst_TX]